### ISSUE TITLE
Installation fails on Raspbian 10

### ISSUE THREAD

**Issue by GabrieleZucca** [r-lib/later#120] opened 2020-03-12 18:48 UTC
When I try to install this package on a Raspberrypi 4 with Raspbian 10 I obtain the following error.

```
> install.packages("later")
[...]
Error: package or namespace load failed for ‘later’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/later/libs/later.so':
  /home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/later/libs/later.so: undefined symbol: __atomic_fetch_add_8
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/pi/R/arm-unknown-linux-gnueabihf-library/3.5/later’

The downloaded source packages are in
        ‘/tmp/RtmplRUphj/downloaded_packages’
Warning message:
In install.packages("later") :
  installation of package ‘later’ had non-zero exit status
```

Info on my system:

```
$ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ R --version
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: arm-unknown-linux-gnueabihf (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

$ uname -a
Linux raspberrypi-gabriele 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```

**Comment by wch** [comment] 2020-03-12 19:07
This is a duplicate of #73 and #109, and is fixed in the development version of later. You can install with

```
remotes::install_github('r-lib/later')
```

**Closed by wch** 2020-03-12 19:07 UTC

**Comment by GabrieleZucca** [comment] 2020-03-12 19:11
I'm sorry, I checked the open issues but not the closed ones. Thanks
